Fix curly brace issue that broke JSON in osc-parse
Fixes the following error (extra } made JSON incorrect):

Error: Invalid JSON (Unexpected RIGHT_BRACE("}") in state VALUE)
        at Parser.proto.parseError (/usr/lib/node_modules/json2csv/node_modules/jsonparse/jsonparse.js:321:16)
        at Parser.proto.onToken (/usr/lib/node_modules/json2csv/node_modules/jsonparse/jsonparse.js:373:21)
        at Parser.parser.onToken (/usr/lib/node_modules/json2csv/lib/JSON2CSVTransform.js:114:24)
        at Parser.proto.write (/usr/lib/node_modules/json2csv/node_modules/jsonparse/jsonparse.js:135:34)
        at JSON2CSVTransform._transform (/usr/lib/node_modules/json2csv/lib/JSON2CSVTransform.js:156:17)
        at JSON2CSVTransform.Transform._read (_stream_transform.js:191:10)
        at JSON2CSVTransform.Transform._write (_stream_transform.js:179:12)
        at doWrite (_stream_writable.js:454:12)
        at writeOrBuffer (_stream_writable.js:436:5)
        at JSON2CSVTransform.Writable.write (_stream_writable.js:327:11)